<?php
/**
 * Image.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\ImageModule\HookSubscriber;

use MU\ImageModule\HookSubscriber\Base\AbstractPictureFilterHooksSubscriber;

/**
 * Implementation class for filter hooks subscriber.
 */
class PictureFilterHooksSubscriber extends AbstractPictureFilterHooksSubscriber
{
    // feel free to add your own convenience methods here
}
