<?php
/**
 * Image.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\ImageModule\Container;

use MU\ImageModule\Container\Base\AbstractHookContainer;

/**
 * Implementation class for hook container methods.
 */
class HookContainer extends AbstractHookContainer
{
    // feel free to add your own convenience methods here
}
