<?php
/**
 * Image.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ImageModule\Listener;

use MU\ImageModule\Listener\Base\AbstractModuleDispatchListener;

/**
 * Event handler implementation class for dispatching modules.
 */
class ModuleDispatchListener extends AbstractModuleDispatchListener
{
    // feel free to enhance the parent methods
}
