<?php
/**
 * MUImage.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUImage
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Paginator switch implementation class for 1.3.x modules.
 */
class MUImage_Paginator_LegacyPaginator extends MUImage_Paginator_Base_LegacyPaginator
{
    // extend the paginator class here if desired
}
