<?php
/**
 * MUImage.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace MU\MUImageModule\Helper;

use MU\MUImageModule\Helper\Base\WorkflowHelper as BaseWorkflowHelper;

/**
 * Utility implementation class for workflow helper methods.
 */
class WorkflowHelper extends BaseWorkflowHelper
{
    // feel free to add your own convenience methods here
}
