services:
    # Entity factory classes
    mu_muimage_module.album_factory:
        class: MU\MUImageModule\Entity\Factory\AlbumFactory
        arguments: ["@doctrine.orm.entity_manager", MU\MUImageModule\Entity\AlbumEntity]
    
    mu_muimage_module.picture_factory:
        class: MU\MUImageModule\Entity\Factory\PictureFactory
        arguments: ["@doctrine.orm.entity_manager", MU\MUImageModule\Entity\PictureEntity]
    
