services:
    # Form types
    
    mu_muimage_module.form.type.albumquicknav:
        class: MU\MUImageModule\Form\Type\QuickNavigation\AlbumQuickNavType
        arguments: ["@translator.default", "@request_stack", "@mu_muimage_module.listentries_helper"]
        tags:
            - { name: form.type }
    
    mu_muimage_module.form.type.picturequicknav:
        class: MU\MUImageModule\Form\Type\QuickNavigation\PictureQuickNavType
        arguments: ["@translator.default", "@request_stack", "@mu_muimage_module.listentries_helper"]
        tags:
            - { name: form.type }
    
    mu_muimage_module.form.handler.album:
        class: MU\MUImageModule\Form\Handler\Album\EditHandler
        arguments: ["@service_container", "@translator.default", "@request_stack", "@router", "@mu_muimage_module.upload_handler"]
        tags:
            - { name: form.type }
    
    mu_muimage_module.form.type.album:
        class: MU\MUImageModule\Form\Type\AlbumType
        arguments: ["@translator.default", "@mu_muimage_module.album_factory", "@mu_muimage_module.listentries_helper"]
        tags:
            - { name: form.type }
    
    mu_muimage_module.form.handler.picture:
        class: MU\MUImageModule\Form\Handler\Picture\EditHandler
        arguments: ["@service_container", "@translator.default", "@request_stack", "@router", "@mu_muimage_module.upload_handler"]
        tags:
            - { name: form.type }
    
    mu_muimage_module.form.type.picture:
        class: MU\MUImageModule\Form\Type\PictureType
        arguments: ["@translator.default", "@mu_muimage_module.picture_factory", "@mu_muimage_module.listentries_helper"]
        tags:
            - { name: form.type }
    
    mu_muimage_module.form.type.deleteentity:
        class: MU\MUImageModule\Form\DeleteEntityType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }
    
    mu_muimage_module.form.type.block.itemlist:
        class: MU\MUImageModule\Block\Form\Type\ItemListBlockType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }
    
    mu_muimage_module.form.type.albumfinder:
        class: MU\MUImageModule\Form\Type\Finder\AlbumFinderType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }
    
    mu_muimage_module.form.type.picturefinder:
        class: MU\MUImageModule\Form\Type\Finder\PictureFinderType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }
    
    mu_muimage_module.form.type.appsettings:
        class: MU\MUImageModule\Form\AppSettingsType
        arguments: ["@translator.default", "@zikula_extensions_module.api.variable"]
        tags:
            - { name: form.type }
