services:
    # Form field types
    
    mu_image_module.form.type.field.upload:
        class: MU\ImageModule\Form\Type\Field\UploadType
        arguments: ["@translator.default"]
        tags:
            - { name: form.type }
