services:
    mu_image_module.link_container:
        class: MU\ImageModule\Container\LinkContainer
        arguments: ["@translator.default", "@router", "@zikula_permissions_module.api.permission", "@mu_image_module.controller_helper", "@zikula_extensions_module.api.variable", "@zikula_users_module.current_user"]
        tags:
            - { name: zikula.link_container }
