services:
    # Twig extension
    mu_muimage_module.twig_extension:
        class: MU\MUImageModule\Twig\TwigExtension
        arguments: ["@translator.default", "@zikula_extensions_module.api.variable", "@mu_muimage_module.workflow_helper", "@mu_muimage_module.view_helper", "@mu_muimage_module.listentries_helper"]
        public: false
        tags:
            - { name: twig.extension }
