<?php
/**
 * MUImage.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace MU\MUImageModule\Block;

use MU\MUImageModule\Block\Base\ItemListBlock as BaseItemListBlock;

/**
 * Generic item list block implementation class.
 */
class ItemListBlock extends BaseItemListBlock
{
    // feel free to extend the item list block here
}
