<?php
/**
 * MUImage.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUImage
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Fri Feb 17 18:57:24 CET 2012.
 */

/**
 * The muimageCheckAlbumAccess method is checking the album access
 *
 * @return string contingent of Main Ablums, Sub Albums and Pictures
 */
function smarty_function_muimageCheckAlbumAccess($params, $view)
{	
    $albumid = $params['albumid'];
	$result = MUImage_Util_View::checkAlbumAccess($albumid);
	
	if (array_key_exists('assign', $params)) {
	    $view->assign($params['assign'], $result);
	    return;
	}
	return $result;
}
