<?php
/**
 * MUImage.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUImage
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Cache api base class.
 */
class MUImage_Api_Base_Cache extends Zikula_AbstractApi
{
    /**
     * Clear cache for given item. Can be called from other modules to clear an item cache.
     *
     * @param $args['ot']   the treated object type
     * @param $args['item'] the actual object
     */
    public function clearItemCache(array $args = array())
    {
        if (!isset($args['ot']) || !isset($args['item'])) {
            return;
        }
    
        $objectType = $args['ot'];
        $item = $args['item'];
    
        $controllerHelper = new MUImage_Util_Controller($this->serviceManager);
        $utilArgs = array('api' => 'cache', 'action' => 'clearItemCache');
        if (!in_array($objectType, $controllerHelper->getObjectTypes('controllerAction', $utilArgs))) {
            return;
        }
    
        if ($item && !is_array($item) && !is_object($item)) {
            $item = ModUtil::apiFunc($this->name, 'selection', 'getEntity', array('ot' => $objectType, 'id' => $item, 'useJoins' => false, 'slimMode' => true));
        }
    
        if (!$item) {
            return;
        }
    
        $instanceId = $item->createCompositeIdentifier();
    
    
        // Clear View_cache
        $cacheIds = array();
        $cacheIds[] = 'main';
        $cacheIds[] = 'view';
        $cacheIds[] = $instanceId;
        
        
        $cacheIds[] = 'zipUpload';
        $cacheIds[] = 'multiUpload';
        $cacheIds[] = 'external';
        $cacheIds[] = 'editMulti';
    
        $view = Zikula_View::getInstance('MUImage');
        foreach ($cacheIds as $cacheId) {
            $view->clear_cache(null, $cacheId);
        }
    
    
        // Clear Theme_cache
        $cacheIds = array();
        $cacheIds[] = 'homepage'; // for homepage (can be assigned in the Settings module)
        $cacheIds[] = 'MUImage/user/main'; // main function
        $cacheIds[] = 'MUImage/user/view/' . $objectType; // view function (list views)
        $cacheIds[] = 'MUImage/user/display/' . $objectType . '|' . $instanceId; // display function (detail views)
        
        
        $cacheIds[] = 'MUImage/user/zipUpload'; // zip upload function
        $cacheIds[] = 'MUImage/user/multiUpload'; // multi upload function
        $cacheIds[] = 'MUImage/user/external'; // external function
        $cacheIds[] = 'MUImage/user/editMulti'; // edit multi function
        $theme = Zikula_View_Theme::getInstance();
        $theme->clear_cacheid_allthemes($cacheIds);
    }
}
