<?php
/**
 * MUImage.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace MU\MUImageModule\ContentType;

use MU\MUImageModule\ContentType\Base\ItemList as BaseItemList;

/**
 * Generic item list content plugin implementation class.
 */
class ItemList extends BaseItemList
{
    // feel free to extend the content type here
}
