<?php
/**
 * Image.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\ImageModule\Entity\Factory;

use MU\ImageModule\Entity\Factory\Base\AbstractAlbumFactory;

/**
 * Factory class used to retrieve entity and repository instances.
 *
 * This is the concrete factory class for album entities.
 */
class AlbumFactory extends AbstractAlbumFactory
{
    // feel free to customise the manager
}
