services:
    # Event subscribers and listeners
    mu_image_module.entity_lifecycle_listener:
        class: MU\ImageModule\Listener\EntityLifecycleListener
        arguments:
            - "@service_container"
            - "@event_dispatcher"
            - "@logger"
        tags: ['doctrine.event_subscriber']
    
    mu_image_module.kernel_listener:
        class: MU\ImageModule\Listener\KernelListener
        tags: ['kernel.event_subscriber']
    
    mu_image_module.installer_listener:
        class: MU\ImageModule\Listener\InstallerListener
        tags: ['kernel.event_subscriber']
    
    mu_image_module.moduledispatch_listener:
        class: MU\ImageModule\Listener\ModuleDispatchListener
        tags: ['kernel.event_subscriber']
    
    mu_image_module.mailer_listener:
        class: MU\ImageModule\Listener\MailerListener
        tags: ['kernel.event_subscriber']
    
    mu_image_module.theme_listener:
        class: MU\ImageModule\Listener\ThemeListener
        tags: ['kernel.event_subscriber']
    
    mu_image_module.userlogin_listener:
        class: MU\ImageModule\Listener\UserLoginListener
        tags: ['kernel.event_subscriber']
    
    mu_image_module.userlogout_listener:
        class: MU\ImageModule\Listener\UserLogoutListener
        tags: ['kernel.event_subscriber']
    
    mu_image_module.user_listener:
        class: MU\ImageModule\Listener\UserListener
        arguments:
            - "@translator.default"
            - "@mu_image_module.entity_factory"
            - "@zikula_users_module.current_user"
            - "@logger"
        tags: ['kernel.event_subscriber']
    
    mu_image_module.userregistration_listener:
        class: MU\ImageModule\Listener\UserRegistrationListener
        tags: ['kernel.event_subscriber']
    
    mu_image_module.users_listener:
        class: MU\ImageModule\Listener\UsersListener
        tags: ['kernel.event_subscriber']
    
    mu_image_module.group_listener:
        class: MU\ImageModule\Listener\GroupListener
        tags: ['kernel.event_subscriber']
    
    mu_image_module.thirdparty_listener:
        class: MU\ImageModule\Listener\ThirdPartyListener
        arguments:
            - "@filesystem"
            - "@request_stack"
        tags: ['kernel.event_subscriber']
    
    mu_image_module.workflow_events_listener:
        class: MU\ImageModule\Listener\WorkflowEventsListener
        arguments:
            - "@mu_image_module.entity_factory"
            - "@mu_image_module.permission_helper"
        tags: ['kernel.event_subscriber']
    
