services:
    # Form field types
    
    mu_image_module.form.type.field.upload:
        class: MU\ImageModule\Form\Type\Field\UploadType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_image_module.image_helper"
            - "@mu_image_module.upload_helper"
        tags:
            - { name: form.type }
