services:
    # Form field types
    
    mu_image_module.form.type.field.multilist:
        class: MU\ImageModule\Form\Type\Field\MultiListType
        arguments:
            - "@mu_image_module.listentries_helper"
        tags: ['form.type']
    
    mu_image_module.form.type.field.translation:
        class: MU\ImageModule\Form\Type\Field\TranslationType
        tags: ['form.type']
    
    mu_image_module.form.type.field.upload:
        class: MU\ImageModule\Form\Type\Field\UploadType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_image_module.image_helper"
            - "@mu_image_module.upload_helper"
        tags: ['form.type']
