services:
    # Form types
    
    mu_image_module.form.type.albumquicknav:
        class: MU\ImageModule\Form\Type\QuickNavigation\AlbumQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_image_module.entity_display_helper"
            - "@mu_image_module.listentries_helper"
            - "@mu_image_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_image_module.form.type.picturequicknav:
        class: MU\ImageModule\Form\Type\QuickNavigation\PictureQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_image_module.entity_display_helper"
            - "@mu_image_module.listentries_helper"
            - "@mu_image_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_image_module.form.type.avatarquicknav:
        class: MU\ImageModule\Form\Type\QuickNavigation\AvatarQuickNavType
        arguments:
            - "@translator.default"
            - "@mu_image_module.listentries_helper"
            - "@mu_image_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_image_module.form.handler.common:
        abstract: true
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@mu_image_module.entity_factory"
            - "@mu_image_module.controller_helper"
            - "@mu_image_module.model_helper"
            - "@mu_image_module.workflow_helper"
            - "@mu_image_module.hook_helper"
            - "@mu_image_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
    
    
    mu_image_module.form.handler.album:
        class: MU\ImageModule\Form\Handler\Album\EditHandler
        parent: mu_image_module.form.handler.common
    
    mu_image_module.form.type.album:
        class: MU\ImageModule\Form\Type\AlbumType
        arguments:
            - "@translator.default"
            - "@mu_image_module.entity_factory"
            - "@mu_image_module.collection_filter_helper"
            - "@mu_image_module.entity_display_helper"
            - "@mu_image_module.listentries_helper"
            - "@mu_image_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_image_module.form.handler.picture:
        class: MU\ImageModule\Form\Handler\Picture\EditHandler
        parent: mu_image_module.form.handler.common
        
    mu_image_module.form.handler.multipicture:
        class: MU\ImageModule\Form\Handler\Picture\MultiUploadHandler
        parent: mu_image_module.form.handler.common
    
    mu_image_module.form.type.picture:
        class: MU\ImageModule\Form\Type\PictureType
        arguments:
            - "@translator.default"
            - "@mu_image_module.entity_factory"
            - "@mu_image_module.collection_filter_helper"
            - "@mu_image_module.entity_display_helper"
            - "@mu_image_module.listentries_helper"
            - "@mu_image_module.feature_activation_helper"
        tags:
            - { name: form.type }
            
    mu_image_module.form.type.multipicture:
        class: MU\ImageModule\Form\Type\MultiPictureType
        arguments:
            - "@translator.default"
            - "@mu_image_module.entity_factory"
            - "@mu_image_module.collection_filter_helper"
            - "@mu_image_module.entity_display_helper"
            - "@mu_image_module.listentries_helper"
            - "@mu_image_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_image_module.form.handler.avatar:
        class: MU\ImageModule\Form\Handler\Avatar\EditHandler
        parent: mu_image_module.form.handler.common
    
    mu_image_module.form.type.avatar:
        class: MU\ImageModule\Form\Type\AvatarType
        arguments:
            - "@translator.default"
            - "@mu_image_module.entity_factory"
            - "@mu_image_module.listentries_helper"
            - "@mu_image_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_image_module.form.type.block.itemlist:
        class: MU\ImageModule\Block\Form\Type\ItemListBlockType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    mu_image_module.form.type.block.item:
        class: MU\ImageModule\Block\Form\Type\ItemBlockType
        arguments:
            - "@translator.default"
            - "@mu_image_module.entity_factory"
            - "@mu_image_module.entity_display_helper"
        tags:
            - { name: form.type }
    
    mu_image_module.form.type.albumfinder:
        class: MU\ImageModule\Form\Type\Finder\AlbumFinderType
        arguments:
            - "@translator.default"
            - "@mu_image_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_image_module.form.type.picturefinder:
        class: MU\ImageModule\Form\Type\Finder\PictureFinderType
        arguments:
            - "@translator.default"
            - "@mu_image_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_image_module.form.type.avatarfinder:
        class: MU\ImageModule\Form\Type\Finder\AvatarFinderType
        arguments:
            - "@translator.default"
            - "@mu_image_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_image_module.form.type.config:
        class: MU\ImageModule\Form\Type\ConfigType
        arguments:
            - "@translator.default"
            - "@=service('zikula_extensions_module.api.variable').getAll('MUImageModule')"
        tags:
            - { name: form.type }
