services:
    # Helper services
    mu_image_module.category_helper:
        class: MU\ImageModule\Helper\CategoryHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@zikula_categories_module.category_registry_repository"
            - "@zikula_categories_module.api.category_permission"
    
    mu_image_module.collection_filter_helper:
        class: MU\ImageModule\Helper\CollectionFilterHelper
        arguments:
            - "@request_stack"
            - "@zikula_users_module.current_user"
            - "@mu_image_module.category_helper"
            - "@=service('zikula_extensions_module.api.variable').get('MUImageModule', 'showOnlyOwnEntries', false)"
    
    mu_image_module.controller_helper:
        class: MU\ImageModule\Helper\ControllerHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@logger"
            - "@form.factory"
            - "@zikula_extensions_module.api.variable"
            - "@mu_image_module.entity_factory"
            - "@mu_image_module.collection_filter_helper"
            - "@mu_image_module.model_helper"
            - "@mu_image_module.image_helper"
            - "@mu_image_module.feature_activation_helper"
    
    mu_image_module.entity_display_helper:
        class: MU\ImageModule\Helper\EntityDisplayHelper
        arguments:
            - "@translator.default"
            - "@mu_image_module.listentries_helper"
    
    mu_image_module.feature_activation_helper:
        class: MU\ImageModule\Helper\FeatureActivationHelper
    
    mu_image_module.hook_helper:
        class: MU\ImageModule\Helper\HookHelper
        arguments:
            - "@hook_dispatcher"
    
    mu_image_module.image_helper:
        class: MU\ImageModule\Helper\ImageHelper
        arguments:
            - "@translator.default"
            - "@session"
            - "@zikula_extensions_module.api.variable"
    
    mu_image_module.listentries_helper:
        class: MU\ImageModule\Helper\ListEntriesHelper
        arguments:
            - "@translator.default"
    
    mu_image_module.model_helper:
        class: MU\ImageModule\Helper\ModelHelper
        arguments:
            - "@mu_image_module.entity_factory"
    
    mu_image_module.search_helper:
        class: MU\ImageModule\Helper\SearchHelper
        arguments:
            - "@translator.default"
            - "@zikula_permissions_module.api.permission"
            - "@session"
            - "@request_stack"
            - "@mu_image_module.entity_factory"
            - "@mu_image_module.controller_helper"
            - "@mu_image_module.entity_display_helper"
            - "@mu_image_module.feature_activation_helper"
            - "@mu_image_module.category_helper"
        tags:
            - { name: zikula.searchable_module, bundleName: MUImageModule }
    
    mu_image_module.upload_helper:
        class: MU\ImageModule\Helper\UploadHelper
        arguments:
            - "@translator.default"
            - "@session"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@=service('zikula_extensions_module.api.variable').getAll('MUImageModule')"
            - "%datadir%"
    
    mu_image_module.view_helper:
        class: MU\ImageModule\Helper\ViewHelper
        arguments:
            - "@twig"
            - "@twig.loader"
            - "@request_stack"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_core.common.theme.pagevars"
            - "@mu_image_module.controller_helper"
    
    mu_image_module.workflow_helper:
        class: MU\ImageModule\Helper\WorkflowHelper
        arguments:
            - "@translator.default"
            - "@workflow.registry"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@mu_image_module.entity_factory"
            - "@mu_image_module.listentries_helper"
