services:
    mu_image_module.link_container:
        class: MU\ImageModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_extensions_module.api.variable"
            - "@mu_image_module.controller_helper"
            - "@mu_image_module.permission_helper"
            - "@request"
        tags: ['zikula.link_container']
