services:
    mu_image_module.link_container:
        class: MU\ImageModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@mu_image_module.controller_helper"
        tags:
            - { name: zikula.link_container }
