services:
    # Custom validators
    mu_image_module.validator.list_entry.validator:
        class: MU\ImageModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@mu_image_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: mu_image_module.validator.list_entry.validator }
