<?php
/**
 * Image.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ImageModule\Block;

use MU\ImageModule\Block\Base\AbstractItemBlock;

/**
 * Generic item detail block implementation class.
 */
class ItemBlock extends AbstractItemBlock
{
    // feel free to extend the item detail block here
}
