<?php
/**
 * MUImage.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace MU\MUImageModule\DependencyInjection;

use MU\MUImageModule\DependencyInjection\Base\MUMUImageExtension as BaseMUMUImageExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class MUMUImageExtension extends BaseMUMUImageExtension
{
    // custom enhancements can go here
}
