<?php
/**
 * Image.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * Permission check for workflow schema 'standard'.
 * This function allows to calculate complex permission checks.
 * It receives the object the workflow engine is being asked to process and the permission level the action requires.
 *
 * @param array  $obj         The currently treated object
 * @param int    $permLevel   The required workflow permission level
 * @param int    $currentUser Id of current user
 * @param string $actionId    Id of the workflow action to be executed
 *
 * @return bool Whether the current user is allowed to execute the action or not
 */
function MUImageModule_workflow_standard_permissioncheck($obj, $permLevel, $currentUser, $actionId)
{
    // calculate the permission component
    $objectType = $obj['_objectType'];
    $component = 'MUImageModule:' . ucfirst($objectType) . ':';

    // calculate the permission instance
    $instance = $obj->createCompositeIdentifier() . '::';

    // now perform the permission check
    $result = SecurityUtil::checkPermission($component, $instance, $permLevel, $currentUser);

    return $result;
}

/**
 * This helper functions cares for including the strings used in the workflow into translation.
 */
function MUImageModule_workflow_standard_gettextstrings()
{
    $serviceManager = \ServiceUtil::getManager();
    $translator = $serviceManager->get('translator.default');
    return [
        'title' => $translator->__('Standard workflow (single approval)'),
        'description' => $translator->__('This is a two staged workflow with stages for untrusted submissions and finally approved publications. It does not allow corrections of non-editors to published pages.'),

        // state titles
        'states' => [
            $translator->__('Initial') => $translator->__('Pseudo-state for content which is just created and not persisted yet.'),
            $translator->__('Waiting') => $translator->__('Content has been submitted and waits for approval.'),
            $translator->__('Approved') => $translator->__('Content has been approved and is available online.'),
            $translator->__('Deleted') => $translator->__('Pseudo-state for content which has been deleted from the database.')
        ],

        // action titles and descriptions for each state
        'actions' => [
            'initial' => [
                $translator->__('Submit') => $translator->__('Submit content for acceptance by a moderator.'),
                $translator->__('Submit and Approve') => $translator->__('Submit content and approve immediately.'),
            ]
            ,
            'waiting' => [
                $translator->__('Update') => $translator->__('Update content.'),
                $translator->__('Approve') => $translator->__('Update content and approve for immediate publishing.'),
                $translator->__('Delete') => $translator->__('Delete content permanently.')
            ]
            ,
            'approved' => [
                $translator->__('Update') => $translator->__('Update content.'),
                $translator->__('Delete') => $translator->__('Delete content permanently.')
            ]
            ,
            'deleted' => [
            ]
        ]
    ];
}
