<?php
/**
 * MUImage.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUImage
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Thu Feb 23 22:43:24 CET 2012.
 */

/**
 * Utility implementation class for image helper methods.
 */
class MUImage_Util_Image extends MUImage_Util_Base_Image
{
	public static function getMetaDatas($imageurl) {

		$dom = ZLanguage::getModuleDomain('MUImage');

		$Exif = exif_read_data($imageurl,'IFD0', true);
		if($Exif === false) {
			$metadatas = __('No metadatas available', $dom);
		}
		else
		{
			$metadatas = '';
			foreach($Exif as $key => $Abschnitt)
			{
				foreach($Abschnitt as $Name => $Wert)
				{
					if ($key != 'APP12' && ($Name != 'FileDateTime' && $Name != 'FileType' && $Name != 'html' && $Name != 'IsColor' && $Name != 'ApertureFNumber' && $Name != 'Orientation' && $Name != 'ImageDescription' && $Name != 'UserCommentEncoding' && $Name != 'SectionsFound'&& $Name != 'ByteOrderMotorola' &&
							$Name != 'ResolutionUnit' && $Name != 'XResolution' && $Name != 'YResolution' && $Name != 'MakerNote' && $Name != 'ExifVersion' && $Name != 'ComponentsConfiguration')) {

						if ($Name == 'FileName') {
							$Name = __('File name', $dom);
						}
						if ($Name == 'FNumber'){
							$Name = __('Aperture', $dom);
							$Wert = (int)$Wert / 10;
						}
						if ($Name == 'ExposureTime') {
							$Name = __('Exposer time: ', $dom);
						}
						if ($Name == 'ISOSpeedRatings') {
							$Name = __('ISO: ', $dom);
						}
						if ($Name == 'WhiteBalance') {
							$Name = __('White balance: ', $dom);
						}
						if ($Name == 'MimeType') {
							$Name = __('Mime type: ', $dom);
						}
						if ($Name == 'Make') {
							$Name = __('Company: ', $dom);
						}
						if ($Name == 'ISOSpeedRatings') {
							$Name = __('ISO: ', $dom);
						}
						if ($Name == 'ISOSpeedRatings') {
							$Name = __('ISO: ', $dom);
						}
						$metadatas .= "$Name: $Wert<br>\n";
					}
				}
			}
		}

		return $metadatas;
	}
}
