<?php
/**
 * Image.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ImageModule\Validator\Constraints;

use MU\ImageModule\Validator\Constraints\Base\AbstractListEntryValidator;

/**
 * List entry validator.
 */
class ListEntryValidator extends AbstractListEntryValidator
{
    // here you can customise the validator
}
