<?php
/**
 * MUImage.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUImage
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Feb 19 15:20:07 CET 2012.
 */

/**
 * Version information base class.
 */
class MUImage_Base_Version extends Zikula_AbstractVersion
{
    public function getMetaData()
    {
        $meta = array();
        // the current module version
        $meta['version'] = '1.0.0';
        // the displayed name of the module
        $meta['displayname'] = $this->__('MUImage');
        // the module description
        $meta['description'] = $this->__('MUImage module generated by ModuleStudio 0.5.4.');
        //! url version of name, should be in lowercase without space
        $meta['url'] = $this->__('muimage');
        // core requirement
        $meta['core_min'] = '1.3.1'; // requires minimum 1.3.1 or later
        $meta['core_max'] = '1.3.99'; // not ready for 1.4.0 yet

        // define special capabilities of this module
        $meta['capabilities'] = array(
            HookUtil::SUBSCRIBER_CAPABLE => array('enabled' => true) /*,
             HookUtil::PROVIDER_CAPABLE => array('enabled' => true), // TODO: see #15
             'authentication' => array('version' => '1.0'),
             'profile'        => array('version' => '1.0', 'anotherkey' => 'anothervalue'),
             'message'        => array('version' => '1.0', 'anotherkey' => 'anothervalue')
             */
        );

        // permission schema
        // DEBUG: permission schema aspect starts
        $meta['securityschema'] = array(
            'MUImage::'             => '::',

            'MUImage:Album:Album'   => 'AlbumID:AlbumID:',

            'MUImage:Album:'        => 'AlbumID::',
            'MUImage:Album:Picture' => 'AlbumID:PictureID:',

            'MUImage:Picture:'      => 'PictureID::'
        );
        // DEBUG: permission schema aspect ends

        return $meta;
    }

    /**
     * Define hook subscriber bundles.
     */
    protected function setupHookBundles()
    {

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.muimage.ui_hooks.albums', 'ui_hooks', __('muimage Albums Display Hooks'));
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'muimage.ui_hooks.albums.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'muimage.ui_hooks.albums.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'muimage.ui_hooks.albums.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'muimage.ui_hooks.albums.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'muimage.ui_hooks.albums.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'muimage.ui_hooks.albums.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'muimage.ui_hooks.albums.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.muimage.filter_hooks.albums', 'filter_hooks', __('muimage Albums Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'muimage.filter_hooks.albums.filter');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.muimage.ui_hooks.pictures', 'ui_hooks', __('muimage Pictures Display Hooks'));
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'muimage.ui_hooks.pictures.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'muimage.ui_hooks.pictures.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'muimage.ui_hooks.pictures.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'muimage.ui_hooks.pictures.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'muimage.ui_hooks.pictures.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'muimage.ui_hooks.pictures.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'muimage.ui_hooks.pictures.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.muimage.filter_hooks.pictures', 'filter_hooks', __('muimage Pictures Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'muimage.filter_hooks.pictures.filter');
        $this->registerHookSubscriberBundle($bundle);

    }
}

