<?php
/**
 * Image.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\ImageModule\Form\Type;

use MU\ImageModule\Form\Type\Base\AbstractAlbumType;

/**
 * Album editing form type implementation class.
 */
class AlbumType extends AbstractAlbumType
{
    // feel free to extend the album editing form type class here
}
