<?php
/**
 * MUImage.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUImage
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Sun Feb 19 15:20:07 CET 2012.
 */

/**
 * Ajax controller class.
 */
class MUImage_Controller_Base_Ajax extends Zikula_Controller_AbstractAjax
{

    /**
     * This method is the default function, and is called whenever the application's
     * Ajax area is called without defining arguments.
     *
     * @return mixed Output.
     */
    public function main($args)
    {
        // DEBUG: permission check aspect starts
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('MUImage::', '::', ACCESS_OVERVIEW));
        // DEBUG: permission check aspect ends

    }

    /**
     * Searches for entities for auto completion usage.
     *
     * @param string $ot       Treated object type.
     * @param string $fragment The fragment of the entered item name.
     * @param string $exclude  Comma separated list with ids of other items (to be excluded from search).
     *
     * @return Zikula_Response_Ajax_Base
     */
    public function getItemList()
    {
        if (!SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_EDIT)) {
            return true;
        }

        $objectType = 'album';
        if ($this->request->isPost() && $this->request->getPost()->has('ot')) {
            $objectType = $this->request->getPost()->filter('ot', 'album', FILTER_SANITIZE_STRING);
        } elseif ($this->request->isGet() && $this->request->getGet()->has('ot')) {
            $objectType = $this->request->getGet()->filter('ot', 'album', FILTER_SANITIZE_STRING);
        }
        if (!in_array($objectType, MUImage_Util_Controller::getObjectTypes('controllerAction', array('controller' => 'ajax', 'action' => 'getItemList')))) {
            $objectType = MUImage_Util_Controller::getDefaultObjectType('controllerAction', array('controller' => 'ajax', 'action' => 'getItemList'));
        }

        $repository = $this->entityManager->getRepository('MUImage_Entity_' . ucfirst($objectType));
        $idFields = ModUtil::apiFunc($this->name, 'selection', 'getIdFields', array('ot' => $objectType));

        $fragment = '';
        $exclude = '';
        if ($this->request->isPost() && $this->request->getPost()->has('fragment')) {
            $fragment = $this->request->getPost()->get('fragment', '');
            $exclude = $this->request->getPost()->get('exclude', '');
        } elseif ($this->request->isGet() && $this->request->getGet()->has('fragment')) {
            $fragment = $this->request->getGet()->get('fragment', '');
            $exclude = $this->request->getGet()->get('exclude', '');
        }
        $exclude = ((!empty($exclude)) ? array($exclude) : array());

        // parameter for used sorting field
        $sort = $this->request->getGet()->get('sort', '');
        if (empty($sort) || !in_array($sort, $repository->getAllowedSortingFields())) {
            $sort = $repository->getDefaultSortingField();
        }
        $sortParam = $sort . ' asc';

        $currentPage = 1;
        $resultsPerPage = 20;

        // get objects from database
        list($entities, $objectCount) = $repository->selectSearch($fragment, $exclude, $sortParam, $currentPage, $resultsPerPage);

        $out = '<ul>';
        if ((is_array($entities) || is_object($entities)) && count($entities) > 0) {
            $titleFieldName = $repository->getTitleFieldName();
            $descriptionFieldName = $repository->getDescriptionFieldName();
            $previewFieldName = $repository->getPreviewFieldName();

            $thumbWidth = 100;
            $thumbHeight = 80;
            foreach ($entities as $item) {
                // class="informal" --> show in dropdown, but do not copy in the input field after selection
                $itemTitle = ((!empty($titleFieldName)) ? $item[$titleFieldName] : $this->__('Item'));
                $itemTitleStripped = str_replace('"', '', $itemTitle);
                $itemDescription = ((isset($item[$descriptionFieldName]) && !empty($item[$descriptionFieldName])) ? $item[$descriptionFieldName] : ''); //$this->__('No description yet.'));
                $itemId = '';
                foreach ($idFields as $idField) {
                    $itemId .= ((!empty($itemId)) ? '_' : '') . $item[$idField];
                }
                $out .= '<li id="' . $itemId . '" title="' . $itemTitleStripped . '">';
                $out .= '<div class="itemtitle">' . $itemTitle . '</div>';
                if (!empty($itemDescription)) {
                    $out .= '<div class="itemdesc informal">' . $itemDescription . '</div>';
                }
                // check for preview image
                if (!empty($previewFieldName) && !empty($item[$previewFieldName]) && isset($item[$previewFieldName . 'FullPath'])) {
                    $thumbImagePath = MUImage_Util_Image::getThumb($item[$previewFieldName], $item[$previewFieldName . 'FullPath'], $thumbWidth, $thumbHeight);
                    $preview = '<img src="' . $thumbImagePath . '" width="' . $thumbWidth . '" height="' . $thumbHeight . '" alt="' . $itemTitleStripped . '" />';
                    $out .= '<div class="itempreview informal" id="itempreview' . $itemId . '">' . $preview . '</div>';
                }
                $out .= '</li>';
            }
        }
        $out .= '</ul>';
        return new Zikula_Response_Ajax_Plain($out);
    }

    /**
     * Checks whether a field value is a duplicate or not.
     *
     * @param string $ot       Treated object type.
     * @param string $fragment The fragment of the entered item name.
     * @param string $exclude  Comma separated list with ids of other items (to be excluded from search).
     *
     * @throws Zikula_Exception If something fatal occurs.
     *
     * @return Zikula_Response_Ajax_Base
     */
    public function checkForDuplicate()
    {
        $this->checkAjaxToken();
        $this->throwForbiddenUnless(SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_EDIT));

        $objectType = $this->request->getPost()->filter('ot', 'album', FILTER_SANITIZE_STRING);
        if (!in_array($objectType, MUImage_Util_Controller::getObjectTypes('controllerAction', array('controller' => 'ajax', 'action' => 'checkForDuplicate')))) {
            $objectType = MUImage_Util_Controller::getDefaultObjectType('controllerAction', array('controller' => 'ajax', 'action' => 'checkForDuplicate'));
        }

        $fieldName = $this->request->getPost()->filter('fn', '', FILTER_SANITIZE_STRING);
        $value = $this->request->getPost()->get('v', '');

        if (empty($fieldName) || empty($value)) {
            return new Zikula_Response_Ajax_BadData($this->__('Error: invalid input.'));
        }

        // check if the given field is existing and unique
        $uniqueFields = array();
        switch ($objectType) {
            case 'album':
                $uniqueFields = array('title');
                break;
            case 'picture':
                $uniqueFields = array('title');
                break;
        }
        if (!count($uniqueFields) || !in_array($fieldName, $uniqueFields)) {
            return new Zikula_Response_Ajax_BadData($this->__('Error: invalid input.'));
        }

        $exclude = (int)$this->request->getPost()->filter('ex', 0, FILTER_VALIDATE_INT);

        $entityClass = 'MUImage_Entity_' . ucfirst($objectType);
        $object = new $entityClass();

        $result = false;
        switch ($objectType) {
            case 'album':
                switch ($fieldName) {
                    case 'title':
                        $result = $object->get_validator()->checkIfTitleExists($value, $exclude);
                        break;
                }
                break;
            case 'picture':
                switch ($fieldName) {
                    case 'title':
                        $result = $object->get_validator()->checkIfTitleExists($value, $exclude);
                        break;
                }
                break;
        }

        // return response
        return new Zikula_Response_Ajax(array('isDuplicate' => $result));
    }

    /**
     * Changes a given flag (boolean field) by switching between true and false.
     *
     * @param string $ot    Treated object type.
     * @param string $field The field to be toggled.
     * @param int    $id    Identifier of treated entity.
     *
     * @return Zikula_Response_Ajax_Base
     */
    public function toggleFlag()
    {
        $this->throwForbiddenUnless(SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_EDIT));

        $objectType = $this->request->getPost()->filter('ot', '', FILTER_SANITIZE_STRING);
        $field = $this->request->getPost()->filter('field', '', FILTER_SANITIZE_STRING);
        $id = (int)$this->request->getPost()->filter('id', 0, FILTER_VALIDATE_INT);

        if ($id == 0 || ($objectType != 'picture') || ($objectType == 'picture' && !in_array($field, array('showTitle', 'showDescription')))) {
            return new Zikula_Response_Ajax_BadData($this->__('Error: invalid input.'));
        }

        // select data from data source
        $entity = ModUtil::apiFunc($this->name, 'selection', 'getEntity', array('ot' => $objectType, 'id' => $id));
        if ($entity == null) {
            return new Zikula_Response_Ajax_NotFound($this->__('No such item.'));
        }

        // toggle the flag
        $entity[$field] = !$entity[$field];

        // save entity back to database
        $this->entityManager->flush();

        // return response
        return new Zikula_Response_Ajax(array('id'    => $id,
            'state' => $entity[$field]));
    }
}
