<?php
/**
 * MUImage.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\MUImageModule\Base;

use CategoryUtil;
use DBUtil;
use Doctrine\DBAL\Connection;
use EventUtil;
use ModUtil;
use RuntimeException;
use System;
use UserUtil;
use Zikula\Core\AbstractExtensionInstaller;
use Zikula_Workflow_Util;
use Zikula\CategoriesModule\Entity\CategoryRegistryEntity;

/**
 * Installer base class.
 */
class MUImageModuleInstaller extends AbstractExtensionInstaller
{
    /**
     * Install the MUMUImageModule application.
     *
     * @return boolean True on success, or false
     *
     * @throws RuntimeException Thrown if database tables can not be created or another error occurs
     */
    public function install()
    {
        $logger = $this->container->get('logger');
        $userName = $this->container->get('zikula_users_module.current_user')->get('uname');
    
        // Check if upload directories exist and if needed create them
        try {
            $container = $this->container;
            $controllerHelper = new \MU\MUImageModule\Helper\ControllerHelper($container, $container->get('translator.default'), $container->get('session'), $container->get('logger'));
            $controllerHelper->checkAndCreateAllUploadFolders();
        } catch (\Exception $e) {
            $this->addFlash(\Zikula_Session::MESSAGE_ERROR, $e->getMessage());
            $logger->error('{app}: User {user} could not create upload folders during installation. Error details: {errorMessage}.', ['app' => 'MUMUImageModule', 'user' => $userName, 'errorMessage' => $e->getMessage()]);
        
            return false;
        }
        // create all tables from according entity definitions
        try {
            $this->schemaTool->create($this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                $this->addFlash(\Zikula_Session::MESSAGE_ERROR, $this->__('Doctrine Exception') . ': ' . $e->getMessage());
                $logger->error('{app}: User {user} could not create the database tables during installation. Error details: {errorMessage}.', ['app' => 'MUMUImageModule', 'user' => $userName, 'errorMessage' => $e->getMessage()]);
    
                return false;
            }
            $returnMessage = $this->__f('An error was encountered while creating the tables for the %s extension.', ['%s' => 'MUMUImageModule']);
            if (!System::isDevelopmentMode()) {
                $returnMessage .= ' ' . $this->__('Please enable the development mode by editing the /app/config/parameters.yml file (change the env variable to dev) in order to reveal the error details (or look into the log files at /app/logs/).');
            }
            $this->addFlash(\Zikula_Session::MESSAGE_ERROR, $returnMessage);
            $logger->error('{app}: User {user} could not create the database tables during installation. Error details: {errorMessage}.', ['app' => 'MUMUImageModule', 'user' => $userName, 'errorMessage' => $e->getMessage()]);
    
            return false;
        }
    
        // set up all our vars with initial values
        $this->setVar('pagesize', 10);
        $this->setVar('pageSizeAdminAlbums', 10);
        $this->setVar('pageSizeAdminPictures', 10);
        $this->setVar('showTitle', false);
        $this->setVar('showDescription', false);
        $this->setVar('countImageView', false);
        $this->setVar('numberParentAlbums', 1);
        $this->setVar('numberSubAlbums', 2);
        $this->setVar('numberPictures', 20);
        $this->setVar('fileSize', 102400);
        $this->setVar('minWidth', 400);
        $this->setVar('maxWidth', 0);
        $this->setVar('maxHeight', 0);
        $this->setVar('groupForCommonAlbums', );
        $this->setVar('supportCategories', false);
        $this->setVar('supportSubAlbums', false);
        $this->setVar('breadcrumbInFrontend', false);
        $this->setVar('kindOfShowSubAlbums',  'links' );
        $this->setVar('ending', 'html');
        $this->setVar('userDeletePictures', false);
        $this->setVar('slideshow1', false);
        $this->setVar('slide1Interval', 4000);
        $this->setVar('slide1Speed', 1000);
        $this->setVar('createSeveralPictureSizes', false);
        $this->setVar('widthFirst', '');
        $this->setVar('heightFirst', '');
        $this->setVar('widthSecond', '');
        $this->setVar('heightSecond', '');
        $this->setVar('widthThird', '');
        $this->setVar('heightThird', '');
        $this->setVar('shrinkPictures', false);
        $this->setVar('fileNameForTitle', true);
    
        $categoryRegistryIdsPerEntity = [];
    
        // add default entry for category registry (property named Main)
        $categoryApi = new \MU\MUImageModule\Api\CategoryApi($this->container, new \MU\MUImageModule\MUMUImageModule());
        $categoryGlobal = CategoryUtil::getCategoryByPath('/__SYSTEM__/Modules/Global');
    
        $registry = new CategoryRegistryEntity();
        $registry->setModname('MUMUImageModule');
        $registry->setEntityname('Album');
        $registry->setProperty($categoryApi->getPrimaryProperty(['ot' => 'Album']));
        $registry->setCategory_Id($categoryGlobal['id']);
    
        try {
            $entityManager = $this->container->get('doctrine.entitymanager');
            $entityManager->persist($registry);
            $entityManager->flush();
        } catch (\Exception $e) {
            $this->addFlash(\Zikula_Session::MESSAGE_ERROR, $this->__f('Error! Could not create a category registry for the %s entity.', ['%s' => 'album']));
            $logger->error('{app}: User {user} could not create a category registry for {entities} during installation. Error details: {errorMessage}.', ['app' => 'MUMUImageModule', 'user' => $userName, 'entities' => 'albums', 'errorMessage' => $e->getMessage()]);
        }
        $categoryRegistryIdsPerEntity['album'] = $registry->getId();
    
        // create the default data
        $this->createDefaultData($categoryRegistryIdsPerEntity);
    
        // install subscriber hooks
        $this->hookApi->installSubscriberHooks($this->bundle->getMetaData());
        
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the MUMUImageModule application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables can not be updated
     */
    public function upgrade($oldVersion)
    {
    /*
        $logger = $this->container->get('logger');
        $userName = $this->container->get('zikula_users_module.current_user')->get('uname');
    
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case '1.0.0':
                // do something
                // ...
                // update the database schema
                try {
                    $this->schemaTool->update($this->listEntityClasses());
                } catch (\Exception $e) {
                    if (System::isDevelopmentMode()) {
                        $this->addFlash(\Zikula_Session::MESSAGE_ERROR, $this->__('Doctrine Exception') . ': ' . $e->getMessage());
                        $logger->error('{app}: User {user} could not update the database tables during the upgrade. Error details: {errorMessage}.', ['app' => 'MUMUImageModule', 'user' => $userName, 'errorMessage' => $e->getMessage()]);
    
                        return false;
                    }
                    $this->addFlash(\Zikula_Session::MESSAGE_ERROR, $this->__f('An error was encountered while updating tables for the %s extension.', ['%s' => 'MUMUImageModule']));
                    $logger->error('{app}: User {user} could not update the database tables during the ugprade. Error details: {errorMessage}.', ['app' => 'MUMUImageModule', 'user' => $userName, 'errorMessage' => $e->getMessage()]);
    
                    return false;
                }
        }
    
        // Note there are several helpers available for making migration of your extension easier.
        // The following convenience methods are each responsible for a single aspect of upgrading to Zikula 1.4.0.
    
        // here is a possible usage example
        // of course 1.2.3 should match the number you used for the last stable 1.3.x module version.
        /* if ($oldVersion = '1.2.3') {
            // rename module for all modvars
            $this->updateModVarsTo140();
            
            // update extension information about this app
            $this->updateExtensionInfoFor140();
            
            // rename existing permission rules
            $this->renamePermissionsFor140();
            
            // rename existing category registries
            $this->renameCategoryRegistriesFor140();
            
            // rename all tables
            $this->renameTablesFor140();
            
            // remove event handler definitions from database
            $this->dropEventHandlersFromDatabase();
            
            // update module name in the hook tables
            $this->updateHookNamesFor140();
            
            // update module name in the workflows table
            $this->updateWorkflowsFor140();
        } * /
    */
    
        // update successful
        return true;
    }
    
    /**
     * Renames the module name for variables in the module_vars table.
     */
    protected function updateModVarsTo140()
    {
        $dbName = $this->getDbName();
        $conn = $this->getConnection();
    
        $conn->executeQuery("UPDATE $dbName.module_vars
                             SET modname = 'MUMUImageModule'
                             WHERE modname = 'MUImage';
        ");
    }
    
    /**
     * Renames this application in the core's extensions table.
     */
    protected function updateExtensionInfoFor140()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $conn->executeQuery("UPDATE $dbName.modules
                             SET name = 'MUMUImageModule',
                                 directory = 'MU/MUImageModule'
                             WHERE name = 'MUImage';
        ");
    }
    
    /**
     * Renames all permission rules stored for this app.
     */
    protected function renamePermissionsFor140()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $componentLength = strlen('MUImage') + 1;
    
        $conn->executeQuery("UPDATE $dbName.group_perms
                             SET component = CONCAT('MUMUImageModule', SUBSTRING(component, $componentLength))
                             WHERE component LIKE 'MUImage%';
        ");
    }
    
    /**
     * Renames all category registries stored for this app.
     */
    protected function renameCategoryRegistriesFor140()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $componentLength = strlen('MUImage') + 1;
    
        $conn->executeQuery("UPDATE $dbName.categories_registry
                             SET modname = CONCAT('MUMUImageModule', SUBSTRING(modname, $componentLength))
                             WHERE modname LIKE 'MUImage%';
        ");
    }
    
    /**
     * Renames all (existing) tables of this app.
     */
    protected function renameTablesFor140()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $oldPrefix = 'muimage_';
        $oldPrefixLength = strlen($oldPrefix);
        $newPrefix = 'mu_muimage_';
    
        $sm = $conn->getSchemaManager();
        $tables = $sm->listTables();
        foreach ($tables as $table) {
            $tableName = $table->getName();
            if (substr($tableName, 0, $oldPrefixLength) != $oldPrefix) {
                continue;
            }
    
            $newTableName = str_replace($oldPrefix, $newPrefix, $tableName);
    
            $conn->executeQuery("RENAME TABLE $dbName.$tableName
                                 TO $dbName.$newTableName;
            ");
        }
    }
    
    /**
     * Removes event handlers from database as they are now described by service definitions and managed by dependency injection.
     */
    protected function dropEventHandlersFromDatabase()
    {
        EventUtil::unregisterPersistentModuleHandlers('MUImage');
    }
    
    /**
     * Updates the module name in the hook tables.
     */
    protected function updateHookNamesFor140()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $conn->executeQuery("UPDATE $dbName.hook_area
                             SET owner = 'MUMUImageModule'
                             WHERE owner = 'MUImage';
        ");
    
        $componentLength = strlen('subscriber.muimage') + 1;
        $conn->executeQuery("UPDATE $dbName.hook_area
                             SET areaname = CONCAT('subscriber.mumuimagemodule', SUBSTRING(areaname, $componentLength))
                             WHERE areaname LIKE 'subscriber.muimage%';
        ");
    
        $conn->executeQuery("UPDATE $dbName.hook_binding
                             SET sowner = 'MUMUImageModule'
                             WHERE sowner = 'MUImage';
        ");
    
        $conn->executeQuery("UPDATE $dbName.hook_runtime
                             SET sowner = 'MUMUImageModule'
                             WHERE sowner = 'MUImage';
        ");
    
        $componentLength = strlen('muimage') + 1;
        $conn->executeQuery("UPDATE $dbName.hook_runtime
                             SET eventname = CONCAT('mumuimagemodule', SUBSTRING(eventname, $componentLength))
                             WHERE eventname LIKE 'muimage%';
        ");
    
        $conn->executeQuery("UPDATE $dbName.hook_subscriber
                             SET owner = 'MUMUImageModule'
                             WHERE owner = 'MUImage';
        ");
    
        $componentLength = strlen('muimage') + 1;
        $conn->executeQuery("UPDATE $dbName.hook_subscriber
                             SET eventname = CONCAT('mumuimagemodule', SUBSTRING(eventname, $componentLength))
                             WHERE eventname LIKE 'muimage%';
        ");
    }
    
    /**
     * Updates the module name in the workflows table.
     */
    protected function updateWorkflowsFor140()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $conn->executeQuery("UPDATE $dbName.workflows
                             SET module = 'MUMUImageModule'
                             WHERE module = 'MUImage';
        ");
    }
    
    /**
     * Returns connection to the database.
     *
     * @return Connection the current connection
     */
    protected function getConnection()
    {
        $entityManager = $this->container->get('doctrine.entitymanager');
        $connection = $entityManager->getConnection();
    
        return $connection;
    }
    
    /**
     * Returns the name of the default system database.
     *
     * @return string the database name
     */
    protected function getDbName()
    {
        return $this->container->getParameter('database_name');
    }
    
    /**
     * Uninstall MUMUImageModule.
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables or stored workflows can not be removed
     */
    public function uninstall()
    {
        $logger = $this->container->get('logger');
        $userName = $this->container->get('zikula_users_module.current_user')->get('uname');
    
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule('MUMUImageModule');
        if ($result === false) {
            $this->addFlash(\Zikula_Session::MESSAGE_ERROR, $this->__f('An error was encountered while removing stored object workflows for the %s extension.', ['%s' => 'MUMUImageModule']));
            $logger->error('{app}: User {user} could not remove stored object workflows during uninstallation.', ['app' => 'MUMUImageModule', 'user' => $userName]);
    
            return false;
        }
    
        try {
            $this->schemaTool->drop($this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                $this->addFlash(\Zikula_Session::MESSAGE_ERROR, $this->__('Doctrine Exception') . ': ' . $e->getMessage());
                $logger->error('{app}: User {user} could not remove the database tables during uninstallation. Error details: {errorMessage}.', ['app' => 'MUMUImageModule', 'user' => $userName, 'errorMessage' => $e->getMessage()]);
    
                return false;
            }
            $this->addFlash(\Zikula_Session::MESSAGE_ERROR, $this->__f('An error was encountered while dropping tables for the %s extension.', ['%s' => 'MUMUImageModule']));
            $logger->error('{app}: User {user} could not remove the database tables during uninstallation. Error details: {errorMessage}.', ['app' => 'MUMUImageModule', 'user' => $userName, 'errorMessage' => $e->getMessage()]);
    
            return false;
        }
    
        // uninstall subscriber hooks
        $this->hookApi->uninstallSubscriberHooks($this->bundle->getMetaData());
        
    
        // remove all module vars
        $this->delVars();
    
        // remove category registry entries
        ModUtil::dbInfoLoad('ZikulaCategoriesModule');
        DBUtil::deleteWhere('categories_registry', 'modname = \'MUMUImageModule\'');
    
        // remove all thumbnails
        $manager = $this->container->get('systemplugin.imagine.manager');
        $manager->setModule('MUMUImageModule');
        $manager->cleanupModuleThumbs();
    
        // remind user about upload folders not being deleted
        $uploadPath = $this->container->getParameter('datadir') . '/MUMUImageModule/';
        $this->addFlash(\Zikula_Session::MESSAGE_STATUS, $this->__f('The upload directories at [%s] can be removed manually.', ['%s' => $uploadPath]));
    
        // uninstallation successful
        return true;
    }
    
    /**
     * Build array with all entity classes for MUMUImageModule.
     *
     * @return array list of class names
     */
    protected function listEntityClasses()
    {
        $classNames = [];
        $classNames[] = 'MU\MUImageModule\Entity\AlbumEntity';
        $classNames[] = 'MU\MUImageModule\Entity\AlbumCategoryEntity';
        $classNames[] = 'MU\MUImageModule\Entity\PictureEntity';
    
        return $classNames;
    }
    
    /**
     * Create the default data for MUMUImageModule.
     *
     * @param array $categoryRegistryIdsPerEntity List of category registry ids
     *
     * @return void
     */
    protected function createDefaultData($categoryRegistryIdsPerEntity)
    {
        $entityClass = 'MU\MUImageModule\Entity\AlbumEntity';
        $entityManager = $this->container->get('doctrine.entitymanager');
        $entityManager->getRepository($entityClass)->truncateTable();
        $entityClass = 'MU\MUImageModule\Entity\PictureEntity';
        $entityManager = $this->container->get('doctrine.entitymanager');
        $entityManager->getRepository($entityClass)->truncateTable();
    }
}
