<?php
/**
 * MUImage.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace MU\MUImageModule\Form\Extension;

use MU\MUImageModule\Form\Extension\Base\UploadTypeExtension as BaseUploadTypeExtension;

/**
 * File field type extension implementation class.
 */
class UploadTypeExtension extends BaseUploadTypeExtension
{
    // feel free to add your customisation here
}
