<?php
/**
 * Image.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ImageModule\Form\Type\Field;

use MU\ImageModule\Form\Type\Field\Base\AbstractUploadType;

/**
 * Upload field type implementation class.
 */
class UploadType extends AbstractUploadType
{
    // feel free to add your customisation here
}
