<?php
/**
 * Image.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\ImageModule\DependencyInjection;

use MU\ImageModule\DependencyInjection\Base\AbstractMUImageExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class MUImageExtension extends AbstractMUImageExtension
{
    // custom enhancements can go here
}
