<?php
/**
 * MUImage.
 *
 * @copyright Michael Ueberschaer
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUImage
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://www.webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Thu Feb 23 22:43:24 CET 2012.
 */

/**
 * Generic item list content plugin implementation class
 */
class MUImage_ContentType_ItemList extends MUImage_ContentType_Base_ItemList
{
    // feel free to extend the content type here
}

function MUImage_Api_ContentTypes_itemlist($args)
{
    return new MUImage_Api_ContentTypes_itemListPlugin();
}
